settings callback: assume settings.get() works
Don't have to be so paranoid la. *_setting assignments need to be more
robust; this can't protect us from much.

We were getting the exception

  Traceback (most recent call last):
    File "C:\Users\rc\AppData\Roaming\Sublime Text 3\Packages\sublime-text-2-buildview\commands.py", line 12, in callback
      val = settings.get(s_key, not_found)
    File "D:\Program Files\Sublime Text 3\sublime.py", line 925, in get
      return sublime_api.settings_get_default(self.settings_id, key, default)
  TypeError: Value required

This remains undiagnosed; we just sidestep this.