fix implementation of __setattr__
I was getting the exception

  Traceback (most recent call last):
    ...
    File ".\pipe_views.py", line 20, in __init__
    File ".\pipe_views.py", line 17, in __setattr__
  TypeError: super(type, obj): obj must be an instance or subtype of type

This is possibly due to __setattr__() being called at __init__() time,
mentioned in

  http://code.activestate.com/recipes/389916-example-setattr-getattr-overloading/